name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install wkhtmltopdf
      run: |
        sudo apt update
        sudo apt -y install wget
        wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
        sudo apt install ./wkhtmltox_0.12.5-1.bionic_amd64.deb
    - name: build resume
      run: make build
    - uses: actions/upload-artifact@v2
      with:
        name: resume
        path: ./build/
