name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install wkhtmltopdf
      run: |
        wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.1/wkhtmltox-0.12.1_linux-wheezy-i386.deb
        sudo dpkg -i  wkhtmltox-0.12.1_linux-wheezy-i386.deb
    - name: build resume
      run: make build
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ./build/
