name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install wkhtmltopdf
      run: |
        sudo wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
        sudo dpkg -i wkhtmltox_0.12.5-1.bionic_amd64.deb
        sudo apt-get install -f
        sudo ln -s /usr/local/bin/wkhtmltopdf /usr/bin
        sudo ln -s /usr/local/bin/wkhtmltoimage /usr/bin
    - name: install python
      run: sudo apt-get install python
    - name: build resume
      run: make build
    - uses: actions/upload-artifact@v2
      with:
        name: resume
        path: ./build/
