name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install wkhtmltopdf
      run: |
        sudo wget https://builds.wkhtmltopdf.org/0.12.1.3/wkhtmltox_0.12.1.3-1~bionic_amd64.deb
        sudo dpkg -i wkhtmltox_0.12.1.3-1~bionic_amd64.deb
        sudo apt-get install -f
        sudo ln -s /usr/local/bin/wkhtmltopdf /usr/bin
        sudo ln -s /usr/local/bin/wkhtmltoimage /usr/bin
    - name: build resume
      run: make build
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ./build/
